name: CD

on:
  release:
    type: [published] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vm_key
          chmod 600 ~/.ssh/vm_key

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ConnectTimeout=15 \
              -i ~/.ssh/vm_key \
              -p 2449 \
              user@course.prafdin.ru "

          echo 'Pulling latest Docker image...'
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/klon-22800/catty-reminders:latest

          echo 'Stopping old container if exists...'
          docker stop catty-app  true

          echo 'Starting new container...'
          docker run -d \
            --name catty-app \
            -p 8181:8181 \
            --restart unless-stopped \
            ghcr.io/klon-22800/catty-reminders:latest

          echo '✅ Deployment completed!'
        "